# Generated by Django 4.1 on 2022-09-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_id_alter_ticket_id_alter_userfollows_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
